server:
  port: 9090

spring:
  application:
    name: microservicio-users
  datasource:
   driver-class-name: com.mysql.cj.jdbc.driver
   url: jdbc:mysql://loscalhost:3306/aauca_noticias
   username: root
   password:
   type: com.zaxxer.hikari.HikariDataSource
   hikari:
     maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format-sql: true
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    org.springframework: INFO
    com.zaxxer.hikari: INFO                
