server:
  port: 8081

spring:
  application:
    name: microservicio-gateway
  cloud:
    config:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user
          uri: http://localhost:9090
          predicates:
           - Path=/user/**
      routes:
        - id: user
          uri: http://localhost:9091
          predicates:
           - Path=/seccion/**
      routes:
        - id: user
          uri: http://localhost:9093
          predicates:
           - Path=/noticia/**
           
           
           
        
            