server:
  port: 9092
spring:
  application:
    name: microservicio-noticias
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://reseau.proxy.rlwy.net:50065/railway?useSSL=false&serverTimezone=UTC
    username: root
    password: EAyUBbUHuOsQRhZyXWQOYhzjmaXhsOPM
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
jwt:
  secret: ${JWT_SECRET:aauca-noticias-secret-key-minimo-32-caracteres-2026}
eureka:
  instance:
    hostname: microservicio-noticias.onrender.com
  client:
    service-url:
      defaultZone: https://microservicio-de-registro.onrender.com/eureka
logging:
  level:
    org.springframework: INFO
    com.zaxxer.hikari: INFO